# Generated by Django 2.1.5 on 2019-01-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190120_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
