# Generated by Django 2.1.5 on 2019-01-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20190120_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
