# Generated by Django 2.1.5 on 2019-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_imagemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='extension',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
