# Generated by Django 2.1.5 on 2019-01-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_imagemodel_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('logo', models.ImageField(null=True, upload_to='uploads')),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
