# Generated by Django 2.1.5 on 2019-01-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_logomodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
